common: &common
    adapter: mysql2
    host: localhost
    encoding: utf8
    pool: 25

development: &dev
    <<: *common
    username: root
    password: 3DvErBUC
    database: obra_dev

test:
    <<: *common
    username: root
    password: 3DvErBUC
    database: obra_test
